#!/usr/bin/env node
// Unit tests for emit.mjs helpers + core. Stdlib only: `node --test test/emit.test.mjs`
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { sanitize, isIdent, areaOf, normRel, emitModel, EmitError, HEADER, parseArgs, checkModel } from "../skills/likec4-discover/scripts/emit.mjs";

describe("sanitize", () => {
  it("strips illegal chars and guards leading digits", () => {
    assert.equal(sanitize("Predict"), "Predict");
    assert.equal(sanitize("my comp!"), "my_comp_");
    assert.equal(sanitize("1api"), "_1api");
    assert.equal(sanitize(""), "unnamed");
  });
  it("renames reserved words deterministically", () => {
    assert.equal(sanitize("order"), "order_");
    assert.equal(sanitize("Order"), "Order_");
    assert.equal(sanitize("checkout"), "checkout"); // not reserved
  });
});

describe("isIdent / areaOf / normRel", () => {
  it("validates identifiers", () => {
    assert.ok(isIdent("order_"));
    assert.ok(!isIdent("a.pi"));
    assert.ok(!isIdent("1x"));
  });
  it("derives area from first path segment", () => {
    assert.equal(areaOf("serving/app.py"), "serving");
    assert.equal(areaOf("app.py"), "app");
  });
  it("normalizes string and object rels", () => {
    assert.deepEqual(normRel("x.y", "imports"), { to: "x.y", kind: "imports", label: "", line: 0 });
    assert.deepEqual(normRel({ to: "x.y", kind: "kafka", label: "L", line: 3 }, "imports"),
      { to: "x.y", kind: "kafka", label: "L", line: 3 });
  });
});

const IR = {
  elements: [
    { title: "App", file: "serving/app.py", lang: "py", imports: [], calls: [], extends: [], tags: [] },
    { title: "predict", symbol: "predict", file: "serving/app.py", lang: "py", line: 212,
      parent: "serving/app.py", route: "POST /predict", calls: ["decode_image", "json"],
      imports: [], extends: [], tags: [] },
    { title: "decode_image", symbol: "decode_image", file: "serving/app.py", lang: "py", line: 175,
      parent: "serving/app.py", calls: [], imports: [], extends: [], tags: [] },
  ],
};

describe("parseArgs", () => {
  it("parses --check", () => {
    assert.equal(parseArgs(["--in", "a", "--out", "b", "--check"]).check, true);
    assert.equal(parseArgs(["--in", "a", "--out", "b"]).check, false);
  });
  it("parses --drop-symbols", () => {
    assert.equal(parseArgs(["--in", "a", "--out", "b", "--drop-symbols"]).dropSymbols, true);
    assert.equal(parseArgs(["--in", "a", "--out", "b"]).dropSymbols, false);
  });
});

describe("checkModel", () => {
  it("passes on valid output, or skips cleanly without likec4", async () => {
    const out = emitModel({ elements: [
      { title: "App", file: "a/app.py", lang: "py", imports: [], calls: [], extends: [], tags: [] },
    ] }, { system: "s" });
    const res = await checkModel(out);
    if (res.skipped) assert.match(res.reason, /not installed/);
    else assert.deepEqual(res.errors, []);
  });
  it("reports errors on broken DSL when likec4 is present", async () => {
    let hasLikec4 = true;
    try { await import("likec4"); } catch { hasLikec4 = false; }
    if (!hasLikec4) return; // skip path already covered above
    const res = await checkModel({
      spec: "specification { element component }\n",
      model: "model { a = nosuchkind 'A' }\n",
      views: "views { view index { include * } }\n",
    });
    assert.ok(!res.skipped && res.errors.length > 0);
  });
});
describe("emitModel", () => {
  it("emits header, nesting, evidence, and resolves sibling calls to inproc", () => {
    const out = emitModel(IR, { system: "demo" });
    for (const doc of [out.spec, out.model, out.views]) assert.ok(doc.startsWith(HEADER));
    assert.match(out.model, /predict = component 'predict' \{[^}]*description 'POST \/predict'/s);
    assert.match(out.model, /\/\/ evidence: serving\/app\.py:212/);
    assert.match(out.model, /demo\.serving\.app\.predict -\[inproc\]-> demo\.serving\.app\.decode_image/);
    assert.ok(!out.model.includes("#autogenerated"), "no per-element tag spam");
    assert.ok(!out.spec.includes("tag autogenerated"), "spec has no autogenerated tag");
  });
  it("derives file-parent FQN from filename, not title", () => {
    const ir = { elements: [{ ...IR.elements[0], title: "Serving App (renamed)" }] };
    const out = emitModel(ir, { system: "demo" });
    assert.match(out.model, /app = component 'Serving App \(renamed\)'/);
  });
  it("drops symbols identical to their file parent", () => {
    const ir = { elements: [
      { title: "checkout", file: "src/checkout.ts", lang: "ts", imports: [], calls: [], extends: [], tags: [] },
      { title: "checkout", symbol: "checkout", file: "src/checkout.ts", lang: "ts", line: 3,
        parent: "src/checkout.ts", calls: [], imports: [], extends: [], tags: [] },
    ] };
    const out = emitModel(ir, { system: "cloud" });
    assert.equal(out.elements.filter((e) => e.symbol === "checkout").length, 0);
    assert.match(out.notes.join("\n"), /drop redundant symbol/);
  });
  it("fails closed on bad identifier, unknown parent, unknown rel kind", () => {
    assert.throws(() => emitModel({ elements: [{ ...IR.elements[0], fqn: "bad fqn!" }] }), EmitError);
    assert.throws(() => emitModel({ elements: [{ ...IR.elements[1], parent: "nope/x.py" }] }), EmitError);
    const badRel = { elements: [{ ...IR.elements[0], calls: [{ to: "demo.serving.app", kind: "smoke" }] }] };
    assert.throws(() => emitModel(badRel, { system: "demo" }), EmitError);
  });
  it("promoted proposals do not hijack file-parent nesting", () => {
    const ir = { elements: [...IR.elements,
      { fqn: "client", kind: "person", title: "Client", file: "serving/app.py", lang: "py",
        calls: [], imports: [], extends: [], tags: [] }] };
    const out = emitModel(ir, { system: "demo" });
    const predict = out.elements.find((e) => e.symbol === "predict");
    assert.equal(predict.parentFqn, "demo.serving.app");
    assert.match(out.model, /predict = component 'predict'/);
  });
  it("dropSymbols keeps file parents + routes, drops helper symbols", () => {
    const out = emitModel(IR, { system: "demo", dropSymbols: true });
    const symbols = out.elements.map((e) => e.symbol).filter(Boolean);
    assert.deepEqual(symbols, ["predict"]); // route kept, decode_image helper dropped
    assert.match(out.model, /predict = component 'predict'/);
    assert.ok(!out.model.includes("decode_image"), "helper symbol not rendered");
    assert.match(out.notes.join("\n"), /dropped 1 symbol element/);
  });
  it("dropSymbols keeps symbolKind-less file parents", () => {
    const out = emitModel({ elements: [IR.elements[0]] }, { system: "demo", dropSymbols: true });
    assert.ok(out.elements.every((e) => !e.symbol), "no symbol elements survive");
    assert.ok(out.elements.some((e) => e.fqn === "demo.serving.app"), "file parent kept");
  });
});
