#!/usr/bin/env node
// emit.mjs — IR JSON -> spec.c4 / model.c4 / views.c4 via string template (zero deps).
// Usage: node emit.mjs --in <ir.json> --out <dir> [--system <name>]
// IR: { elements: [{fqn?, kind?, title, file, lang, symbol?, line?, parent?, route?, imports?, calls?, extends?, technology?, tags?}], proposals? }
// - relationship entries may be strings (default kind) or {to, kind?, label?, line?} objects.
// - scanner `calls` entries that match a sibling symbol name resolve to inproc edges.
// - provenance: file header comments (no per-element tags — tags render as badges).
// Importable for unit tests: `import { sanitize, emitModel } from './emit.mjs'`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export function help() {
  console.log(`emit.mjs — emit LikeC4 sources from labeled IR
Usage: node emit.mjs --in <ir.json> --out <dir> [--system <name>] [--check]
Fails closed on duplicate FQN, bad identifier, or unknown relationship kind.
--check runs LikeC4.fromSource().getErrors() when the likec4 package is
installed (skipped with a note otherwise); template output stays canonical.`);
}

const IDENT_RE = /^[A-Za-z_][A-Za-z0-9_-]*$/;
export const REL_KINDS = new Set(["http", "kafka", "s3", "promql", "inproc", "calls", "imports", "inherits"]);
// LikeC4 DSL reserved words (verified: `order`; rest are language keywords that
// break parsing in identifier position). Matched case-insensitively.
const RESERVED = new Set([
  "specification", "element", "deploymentnode", "relationship", "tag", "color",
  "model", "views", "view", "deployment", "global", "include", "exclude",
  "extend", "extends", "style", "title", "description", "summary", "notation",
  "technology", "link", "shape", "icon", "border", "opacity", "multiple",
  "navigateto", "autolayout", "order", "group", "node", "instance", "filter",
  "with", "of", "dynamic", "where",
]);
export const sanitize = (s) => {
  let out = String(s).replace(/[^A-Za-z0-9_-]/g, "_").replace(/^([0-9])/, "_$1") || "unnamed";
  if (RESERVED.has(out.toLowerCase())) out = `${out}_`;
  return out;
};
export const isIdent = (s) => IDENT_RE.test(s);

export function parseArgs(argv) {
  const o = { in: "", out: "", system: "cloud", check: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--in") o.in = argv[++i];
    else if (a === "--out") o.out = argv[++i];
    else if (a === "--system") o.system = argv[++i];
    else if (a === "--check") o.check = true;
    else if (a === "-h" || a === "--help") { help(); process.exit(0); }
  }
  if (!o.in || !o.out) { help(); process.exit(2); }
  return o;
}

export function areaOf(file) {
  const parts = String(file || "").split("/");
  return parts.length > 1 ? sanitize(parts[0]) : "app";
}

export function normRel(r, defaultKind) {
  if (typeof r === "string") return { to: r, kind: defaultKind, label: "", line: 0 };
  return { to: r.to, kind: r.kind || defaultKind, label: r.label || "", line: r.line || 0 };
}

export const HEADER = "// Generated by likec4-discover — do not hand-edit. Regenerate via emit.mjs.";

const q = (s) => `'${String(s).replace(/'/g, "\\'")}'`;

function specBlock() {
  return `${HEADER}
specification {
  element person {
    notation 'Person'
    style {
      shape person
      color green
    }
  }
  element system {
    notation 'Software System'
    style {
      color primary
    }
  }
  element container {
    notation 'Container'
    style {
      color blue
    }
  }
  element component {
    notation 'Component'
    style {
      color sky
    }
  }
  element database {
    notation 'Database'
    style {
      shape storage
      color indigo
    }
  }
  relationship http {
    technology 'HTTP'
  }
  relationship kafka {
    technology 'Kafka TCP'
    line dotted
    color amber
  }
  relationship s3 {
    technology 'S3 API'
  }
  relationship promql {
    technology 'PromQL'
  }
  relationship inproc {
    technology 'In-process'
  }
  relationship calls
  relationship imports
  relationship inherits
}
`;
}

// Pure core: IR + options -> {spec, model, views, elements}. Throws EmitError on closed failures.
export class EmitError extends Error {}

export function emitModel(ir, opts = {}) {
  const system = opts.system || "cloud";
  const notes = [];
  const warn = (msg) => notes.push(msg);
  const fail = (msg) => { throw new EmitError(msg); };
  const list = Array.isArray(ir) ? ir : ir.elements ?? [];
  if (!list.length) fail("empty IR");
  if (list.length > 200) warn(`${list.length} elements > 200 default cap`);

  const seen = new Set();
  // Parent refs up front (single pass): file paths + explicit FQNs that have children.
  const parentRefs = new Set();
  for (const c of list) if (c.parent) parentRefs.add(c.parent);
  // Pass 1: parents (no parent ref) and top-level persons.
  const els = new Array(list.length);
  const fileFqn = new Map(); // file path -> assigned FQN
  for (let i = 0; i < list.length; i++) {
    const e = list[i];
    if (e.parent) continue;
    // Default leaf is structural (filename), never the display title: titles are
    // free text and must not shift FQNs between labeling and emit.
    const fileLeaf = e.file ? sanitize(e.file.split("/").pop().split(".")[0]) : null;
    let fqn;
    if (e.fqn) {
      // Explicit FQNs fail closed: a labeling typo must surface, never silently rename.
      if (!String(e.fqn).split(".").every(isIdent)) fail(`bad identifier in FQN: ${e.fqn}`);
      fqn = e.fqn;
    } else fqn = e.kind === "person" ? sanitize(e.title || "actor")
      : `${sanitize(system)}.${areaOf(e.file)}.${sanitize(e.symbol || fileLeaf || e.title || "unnamed")}`;
    if (!String(fqn).split(".").every(isIdent)) fail(`bad identifier in FQN: ${fqn}`);
    let uniq = fqn, n = 2;
    while (seen.has(uniq)) uniq = `${fqn}_${n++}`;
    if (uniq !== fqn) warn(`dedupe: ${fqn} -> ${uniq}`);
    seen.add(uniq);
    const hasChildren = (e.file && parentRefs.has(e.file)) || (e.fqn && parentRefs.has(e.fqn));
    els[i] = { ...e, fqn: uniq, kind: e.kind || (hasChildren ? "container" : "component") };
    // Only true file parents claim a file path (first wins): promoted proposal
    // elements reuse source files as evidence and must not hijack symbol nesting.
    if (e.file && !e.symbol && !fileFqn.has(e.file)) fileFqn.set(e.file, uniq);
  }
  // Pass 2: symbol children nest under the parent FQN.
  for (let i = 0; i < list.length; i++) {
    const e = list[i];
    if (!e.parent) continue;
    const parentFqn = fileFqn.get(e.parent) || (seen.has(e.parent) ? e.parent : null);
    if (!parentFqn) fail(`unknown parent ref: ${e.parent} (file or FQN expected)`);
    let fqn;
    if (e.fqn) {
      if (!String(e.fqn).split(".").every(isIdent)) fail(`bad identifier in FQN: ${e.fqn}`);
      fqn = e.fqn;
    } else fqn = `${parentFqn}.${sanitize(e.symbol || e.title || "unnamed")}`;
    // A symbol identical to its file parent (e.g. function checkout in checkout.ts)
    // would create an illegal same-name nesting level — the parent already represents it.
    if (!e.fqn && sanitize(e.symbol || e.title || "").toLowerCase() === parentFqn.split(".").pop().toLowerCase()) {
      warn(`drop redundant symbol: ${e.file} ${e.symbol} (same as file parent)`);
      els[i] = null;
      continue;
    }
    if (!String(fqn).split(".").every(isIdent)) fail(`bad identifier in FQN: ${fqn}`);
    let uniq = fqn, n = 2;
    while (seen.has(uniq)) uniq = `${fqn}_${n++}`;
    if (uniq !== fqn) warn(`dedupe: ${fqn} -> ${uniq}`);
    seen.add(uniq);
    els[i] = { ...e, fqn: uniq, kind: e.kind || "component", parentFqn };
  }
  const elements = els.filter(Boolean);
  const known = new Set(elements.map((e) => e.fqn));
  // Synthesize missing intermediate ancestors (system -> area containers) so every
  // FQN level has a declaring block. Depths: 1 = system, >1 = container.
  for (const e of [...elements]) {
    if (e.kind === "person") continue;
    const segs = e.fqn.split(".");
    for (let d = 1; d < segs.length; d++) {
      const prefix = segs.slice(0, d).join(".");
      if (!known.has(prefix)) {
        known.add(prefix);
        elements.push({
          fqn: prefix, kind: d === 1 ? "system" : "container", title: segs[d - 1],
          file: "", line: 0, technology: "", tags: [],
          imports: [], calls: [], extends: [],
          parentFqn: d > 1 ? segs.slice(0, d - 1).join(".") : null,
          synthetic: true,
        });
      }
    }
    if (!e.parentFqn && segs.length > 1) e.parentFqn = segs.slice(0, -1).join(".");
  }
  // Sibling symbol lookup for bare-name call resolution: parentFqn -> Map(symbol/title -> fqn).
  const siblings = new Map();
  for (const e of elements) {
    const key = e.parentFqn || e.fqn;
    if (!siblings.has(key)) siblings.set(key, new Map());
    const m = siblings.get(key);
    if (e.symbol) m.set(e.symbol, e.fqn);
    m.set(e.title, e.fqn);
  }

  // Build nesting tree: children grouped under parent FQN; top level = persons + systems.
  const childrenOf = new Map();
  const tops = [];
  for (const e of elements) {
    if (e.parentFqn) {
      if (!childrenOf.has(e.parentFqn)) childrenOf.set(e.parentFqn, []);
      childrenOf.get(e.parentFqn).push(e);
    } else tops.push(e);
  }
  for (const arr of childrenOf.values()) arr.sort((a, b) => a.fqn.localeCompare(b.fqn));
  tops.sort((a, b) => a.fqn.localeCompare(b.fqn));

  function renderEl(e, indent) {
    const pad = "  ".repeat(indent);
    const leaf = e.fqn.split(".").pop();
    const lines = [];
    if (e.file && e.line) lines.push(`${pad}// evidence: ${e.file}:${e.line}`);
    const props = [];
    if (e.technology) props.push(`technology ${q(e.technology)}`);
    if (e.route) props.push(`description ${q(e.route)}`);
    const kids = childrenOf.get(e.fqn) || [];
    lines.push(`${pad}${leaf} = ${e.kind} ${q(e.title)} {`);
    for (const p of props) lines.push(`${pad}  ${p}`);
    for (const k of kids) lines.push(renderEl(k, indent + 1));
    lines.push(`${pad}}`);
    return lines.join("\n");
  }

  let model = `${HEADER}\nmodel {\n`;
  for (const t of tops) model += renderEl(t, 1) + "\n";
  // Relationships at model top level (never parent-child).
  for (const e of elements) {
    const rels = [
      ...(e.imports || []).map((r) => normRel(r, "imports")),
      ...(e.calls || []).map((r) => (typeof r === "object" ? normRel(r, "inproc") : null)).filter(Boolean),
    ];
    // Resolve bare scanner call names to sibling symbols -> inproc.
    if (e.parentFqn || siblings.has(e.fqn)) {
      const sib = siblings.get(e.parentFqn || e.fqn);
      for (const c of e.calls || []) {
        if (typeof c !== "string") continue;
        const target = sib.get(c);
        if (target && target !== e.fqn && !rels.some((r) => r.to === target)) {
          rels.push({ to: target, kind: "inproc", label: "", line: e.line || 0 });
        }
      }
    }
    for (const r of rels) {
      if (!known.has(r.to)) continue;
      if (!REL_KINDS.has(r.kind)) fail(`unknown relationship kind: ${r.kind} (${e.fqn})`);
      if (r.to === e.fqn || e.fqn.startsWith(r.to + ".") || r.to.startsWith(e.fqn + ".")) continue;
      if (e.file && (r.line || e.line)) model += `  // evidence: ${e.file}:${r.line || e.line}\n`;
      model += r.kind === "imports" && !r.label
        ? `  ${e.fqn} -> ${r.to}\n`
        : `  ${e.fqn} -[${r.kind}]-> ${r.to}${r.label ? ` ${q(r.label)}` : ""}\n`;
    }
  }
  model += "}\n";

  const systems = new Set(elements.filter((e) => !e.parentFqn && e.kind !== "person").map((e) => e.fqn.split(".")[0]));
  let views = `${HEADER}\nviews {
  view index {
    title 'Landscape'
    include *
    autoLayout LeftRight
  }
`;
  for (const sys of [...systems].sort()) {
    views += `  view of_${sys} of ${sys} {\n    title '${sys}'\n    include *\n    autoLayout LeftRight\n  }\n`;
  }
  views += "}\n";

  return { spec: specBlock(), model, views, elements, notes };
}

// Optional programmatic cross-check (Hybrid half): LikeC4.fromSource().getErrors()
// when likec4 is installed. Dynamic import only — core path stays dependency-free.
export async function checkModel(out) {
  let LikeC4;
  try {
    ({ LikeC4 } = await import("likec4"));
  } catch {
    return { skipped: true, reason: "likec4 package not installed" };
  }
  const likec4 = await LikeC4.fromSource(`${out.spec}\n${out.model}\n${out.views}`);
  const errors = likec4.getErrors();
  if (typeof likec4.dispose === "function") await likec4.dispose().catch(() => {});
  return { skipped: false, errors };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const raw = JSON.parse(readFileSync(args.in, "utf8"));
  let out;
  try {
    out = emitModel(raw, { system: args.system });
  } catch (e) {
    if (e instanceof EmitError) { console.error(`emit.mjs: ${e.message}`); process.exit(4); }
    throw e;
  }
  for (const n of out.notes) console.error(`emit.mjs: ${n}`);
  mkdirSync(args.out, { recursive: true });
  writeFileSync(join(args.out, "spec.c4"), out.spec);
  writeFileSync(join(args.out, "model.c4"), out.model);
  writeFileSync(join(args.out, "views.c4"), out.views);
  console.error(`emit.mjs: ${out.elements.length} elements -> ${args.out}/spec.c4,model.c4,views.c4`);
  if (args.check) {
    const res = await checkModel(out);
    if (res.skipped) {
      console.error(`emit.mjs: --check skipped (${res.reason})`);
    } else if (res.errors.length) {
      console.error(`emit.mjs: --check FAILED with ${res.errors.length} error(s):`);
      for (const e of res.errors.slice(0, 10)) console.error(`  - ${e.message || JSON.stringify(e).slice(0, 200)}`);
      process.exit(4);
    } else {
      console.error("emit.mjs: --check passed (getErrors() empty)");
    }
  }
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
