#!/usr/bin/env bash
# validate-fixtures.sh — CI gate: scan -> emit -> likec4 validate (likec4 1.59.3).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

for fx in tiny-ts tiny-py tiny-api tiny-tsconfig ignore-probe; do
  echo "--- fixture: $fx ---"
  node "$ROOT/skills/likec4-discover/scripts/scan.mjs" --root "$ROOT/fixtures/$fx" --out "$OUT/$fx.ir.json"
  node "$ROOT/skills/likec4-discover/scripts/emit.mjs" --in "$OUT/$fx.ir.json" --out "$OUT/$fx"
  npx -y likec4@1.59.3 validate --no-layout --json "$OUT/$fx" | tee "$OUT/$fx.json"
  node -e "const r=require('$OUT/$fx.json'); if(!r.valid||r.stats.filteredErrors!==0){console.error('VALIDATION FAILED');process.exit(1)} console.log('OK: valid, filteredErrors=0')"
  grep -q "^// Generated by likec4-discover" "$OUT/$fx/spec.c4" "$OUT/$fx/model.c4" "$OUT/$fx/views.c4" \
    || { echo "MISSING provenance header"; exit 1; }
  if grep -q "#autogenerated" "$OUT/$fx"/*.c4; then echo "TAG SPAM detected"; exit 1; fi
  echo "OK: provenance header present, no tag spam"
done

echo "--- fixture assertions: tiny-api symbols + proposals ---"
node -e "
const ir = require('$OUT/tiny-api.ir.json');
const kinds = new Set(ir.elements.map((e) => e.symbolKind).filter(Boolean));
for (const k of ['class', 'function', 'route']) {
  if (!kinds.has(k)) { console.error('missing symbolKind: ' + k); process.exit(1); }
}
const routes = ir.elements.filter((e) => e.symbolKind === 'route').map((e) => e.route);
if (!routes.includes('GET /health') || !routes.includes('POST /predict')) { console.error('missing routes: ' + JSON.stringify(routes)); process.exit(1); }
const inproc = ir.elements.find((e) => e.symbol === 'predict').calls;
if (!inproc.includes('load_model')) { console.error('missing same-file call edge'); process.exit(1); }
const titles = ir.proposals.map((p) => p.title);
for (const t of ['tiny-api', 'Prometheus']) {
  if (!titles.some((x) => x.includes(t))) { console.error('missing proposal: ' + t); process.exit(1); }
}
console.log('OK: symbols, routes, inproc calls, proposals present');
"
echo "--- fixture assertions: tiny-tsconfig aliases + nest + actor ---"
node -e "
const ir = require('$OUT/tiny-tsconfig.ir.json');
const main = ir.elements.find((e) => e.file === 'src/main.ts' && !e.symbol);
const alias = (main.aliasImports || []).find((a) => a.from === '@app/store');
if (!alias || alias.to !== 'src/store') { console.error('alias not resolved: ' + JSON.stringify(main.aliasImports)); process.exit(1); }
const bare = (main.aliasImports || []).find((a) => a.from === 'store');
if (!bare || bare.to !== 'src/store') { console.error('baseUrl bare import not resolved: ' + JSON.stringify(main.aliasImports)); process.exit(1); }
const routes = ir.elements.filter((e) => e.symbolKind === 'route').map((e) => e.route);
if (!routes.includes('GET /cats') || !routes.includes('POST /cats')) { console.error('missing nest routes: ' + JSON.stringify(routes)); process.exit(1); }
const vercel = ir.elements.find((e) => e.route === 'POST /api/chat');
if (!vercel || vercel.symbol !== 'POST') { console.error('vercel handler must keep code identifier as symbol'); process.exit(1); }
const chained = ir.elements.filter((e) => e.file === 'src/users.route.js' && e.symbolKind === 'route').map((e) => e.route);
for (const r of ['GET /', 'GET /:userId', 'PATCH /:userId']) {
  if (!chained.includes(r)) { console.error('missing chained route: ' + r + ' got ' + JSON.stringify(chained)); process.exit(1); }
}
const arrows = ir.elements.find((e) => e.file === 'src/users.route.js' && e.symbol === 'createUser');
if (!arrows || arrows.symbolKind !== 'function') { console.error('wrapped arrow handler not detected'); process.exit(1); }
const plain = ir.elements.find((e) => e.file === 'src/users.route.js' && e.symbol === 'plain');
if (plain) { console.error('plain const wrongly detected as function'); process.exit(1); }
const actor = ir.proposals.find((p) => p.kind === 'person' && p.title === 'Client');
if (!actor) { console.error('missing Client actor proposal'); process.exit(1); }
console.log('OK: tsconfig alias, nest routes, actor proposal present');
"
echo "--- fixture assertions: ignore-probe keeps database.ts ---"
node -e "
const ir = require('$OUT/ignore-probe.ir.json');
if (!ir.elements.some((e) => e.file === 'src/database.ts')) { console.error('database.ts wrongly excluded by data/ entry'); process.exit(1); }
console.log('OK: data/ does not exclude database.ts');
"
echo "--- quick one-liner on tiny-api ---"
rm -rf "$OUT/quick" && "$ROOT/skills/likec4-discover/scripts/discover.sh" quick --root "$ROOT/fixtures/tiny-api" --out "$OUT/quick" --system demo >/dev/null 2>&1 \
  || { echo "QUICK ONE-LINER FAILED"; exit 1; }
echo "OK: discover.sh quick passes end-to-end"
echo "--- quick --granularity file on tiny-api (file-level + routes) ---"
rm -rf "$OUT/quick-file" && "$ROOT/skills/likec4-discover/scripts/discover.sh" quick --root "$ROOT/fixtures/tiny-api" --out "$OUT/quick-file" --system demo --granularity file >/dev/null 2>&1 \
  || { echo "QUICK FILE GRANULARITY FAILED"; exit 1; }
node -e "
const fs = require('fs');
const model = fs.readFileSync('$OUT/quick-file/model.c4', 'utf8');
const comps = (model.match(/= component /g) || []).length;
if (comps > 12) { console.error('file granularity did not prune: ' + comps + ' components'); process.exit(1); }
for (const r of ['POST /predict', 'GET /health']) {
  if (!model.includes(r)) { console.error('route lost in file mode: ' + r); process.exit(1); }
}
if (model.includes('load_model = component') || model.includes('decode_image = component')) { console.error('helper symbol leaked into file mode'); process.exit(1); }
console.log('OK: file granularity keeps routes, drops helpers (' + comps + ' components)');
"
npx -y likec4@1.59.3 validate --no-layout --json "$OUT/quick-file" | \
  node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const r=JSON.parse(s);if(!r.valid||r.stats.filteredErrors!==0){console.error('VALIDATION FAILED');process.exit(1)}console.log('OK: file-mode output validates')})"
echo "all fixtures validated"
